import js from "@eslint/js"
import globals from "globals"
import reactHooks from "eslint-plugin-react-hooks"

import tseslint from "typescript-eslint"
import simpleImportSort from "eslint-plugin-simple-import-sort" // Import the plugin
import reactRefresh from "eslint-plugin-react-refresh"

export default tseslint.config(
    // removed eslint from src/components/ui foldersince it is auto generated by the UI library.
    { ignores: ["dist", "src/components/ui/*"] },
    {
        extends: [js.configs.recommended, ...tseslint.configs.recommended],
        files: ["**/*.{ts,tsx}"],
        languageOptions: {
            ecmaVersion: 2020,
            globals: globals.browser,
        },
        plugins: {
            "react-hooks": reactHooks,
            "react-refresh": reactRefresh,
            "simple-import-sort": simpleImportSort, // Add the plugin here
        },
        rules: {
            ...reactHooks.configs.recommended.rules,
            "react-refresh/only-export-components": [
                "warn",
                { allowConstantExport: true },
            ],
            "simple-import-sort/imports": "error", // Add the sorting rule for imports
            "simple-import-sort/exports": "error", // Optional: Add the sorting rule for exports
        },
    }
)
